# Generated by Django 3.2.6 on 2021-08-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='link',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='url',
            name='uuid',
        ),
    ]
